apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:nfOr/zFcJP/8P1DD/c0Oh06TsBUTT6tZcBd2Z8rp/vQ8gyCjJD2G5C6grROiHDV6w5jram6ONqcwhKzm9Fx+3uZ2xG7mvFXHMMQExxbF3oUoCYTYqQLos7uRybCvI+Sgtw==,iv:vXY1DT+UOVWc3UxDCSyKmJrmYBuUwXKJFp5pSHcnDek=,tag:ta8FIZCxJevfIbKZ3QPSWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMXZtcHo2SE9ndmlTYUxE
            MTNHZFJqTkhBRnh6M09SYjk4ZzNxTWtIMTE4CjZnOWplMmV1MWdqV1RqUE91ZGgx
            cjVuQTVUQWY4U21haFdNZ2crbmNxUEUKLS0tIHZ1K3BjZjhHTzJOSUpCMXFueWNZ
            QjdueVpheGRicVZSYzNyNlRBM29EODQKk6amDvFmYTGNIYx1bq1yKcLX/wD0/xZ6
            biBdfo+LTXCDjd937RiSae0b+5kDc/w9OjNEaX94cNSsV7NbER6T5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-06-30T13:28:18Z"
    mac: ENC[AES256_GCM,data:XXF05mb0a1YkDZFyp/AGVNI6gMgUOS3dwRUrieCyC6iTEYdraTziHHAw8mLMyZEOdU0vW5WEchfd/2yzG74wl44OYumCmXzlIc8MJiGV6ipBPrwh4sSZoh3oa0/crgFf913MeMdSEpGMlMOjOG5h2XHPSEi9BBs1siJfD8ulheA=,iv:WQPOPSNX06tCCChi0fUSzTIlyy6KZ/x9fviPc9rbhBk=,tag:BQ1nH9r4kr9w4QVsDpnMCg==,type:str]
    version: 3.13.1
