apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:AjbbDir1ARG5e4LVIAzXjdYHHtlcGIO6IaJqo+uK1Doebn08b/yoqKEoQ7pt23MPYkt/3XzJ6f69XKgnYgegpgE9nrsl0N+aiUCaX8W/WFxNqWGVP5b7D5yAjrVr/P5y9A==,iv:lprvhBeFWrEOPT7SgWfdsfxKMv6cfWsZL1qSeVPSDXg=,tag:9MQ8jWv6H+MNAutEBID6fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL1FCa01qNGxhSmxkZ3hn
            NElQUnl1WUtmNi9sOU9LbmtHWTZWc0RpT1JNClpZZ085bndsSnREY0xMd1RYbDZv
            c2JiUndmRmYrak5lTlF1Qko4eUsxYzQKLS0tIFJ4bDN0cjZrODlXcFJXOCtwUjR3
            ZDl5RzI0S0F0TUF5MXRGemRQUkJ5N28KPANbmls/hvFKPrN/p7J3E/7EGurGHKuA
            dvIDajR2sqDFhbU0B9rRZ02Ha2iJsIb0BPo6D45rNI23DDPtNztJdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-06-30T13:35:48Z"
    mac: ENC[AES256_GCM,data:a+DH9N+eAYnZWR0bOU9E+Q8TYI6DygKvfczFdWHecze4R3k5gTDYzy3BSoq0psR4dpILcjaQWzQv0054776AYIDvDFNYBVlvvh5j4t5U7P8T9fJwPxYbMbc6wiK3iIVFFHN0Atx4aOJHPZ1EajT2ETysnl4UPscgwQiJ98juq7U=,iv:zpX7UBasrvFwMaG9IkBIqR9rSHrNrVwnJz0jpPzFWss=,tag:1HBB8UlI3M5FU27IwbCI1g==,type:str]
    version: 3.13.1
